apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sam
  namespace: argocd
spec:
  destination:
    namespace: samns
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/shekhawatajit/sam.git'
    path: deploy/helm
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
syncPolicy:
  syncOptions:
    - CreateNamespace=true
