apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sam
  namespace: argocd
spec:
  destination:
    namespace: samns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/helm
    repoURL: https://github.com/shekhawatajit/sam.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    