name: my-sample-app
version: 0.1.0
description: A fullstack application with a React frontend and a Python backend.

# -- Image name and version
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/shekhawatajit/samfrontend
  tag: release

# -- nginx port
port: 3000

# -- Upstream host
backendServiceName:

ingress:
  # -- Enable ingress
  enabled: true
  # -- Ingress name
  # @default -- .Release.Name
  name:
  # -- Domain
  domain: romanow-alex.ru

# -- Additional env variables
environments: []

# -- Additional secrets
secrets: []

resources:
  # -- Requested resources
  requests:
    cpu: 100m
    memory: 128Mi
  # -- Limited resources
  limits:
    cpu: 200m
    memory: 128Mi
