name: my-fullstack-app
version: 0.1.0
description: A fullstack application with a React frontend and a Python backend.

frontend:
  image:
    repository: ghcr.io/shekhawatajit/sambackend:latest
    tag: latest
  service:
    type: ClusterIP
    port: 80

backend:
  image:
    repository: ghcr.io/shekhawatajit/samfrontend:latest
    tag: latest
  service:
    type: ClusterIP
    port: 5000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"